version: '3.7'
services:
  postgres:
    container_name: postgres
    ports:
      - '5432:5432'
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: levon
      POSTGRES_PASSWORD: ModernAudiophilesMostComplexPasswordCouldBeBetter
    volumes:
      - postgres:/var/lib/postgres
  prisma:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  backend:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes: #define our postgres volume used above
  postgres: